version: '3'

volumes:
  db_data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT_DB}
      DB_HOST: db
      DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
  db:
    image: mysql:latest
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
      DB_NAME: primary_store
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

